name: Validate Integration

on:
  push:
    branches: [main] # Or your default branch
  pull_request:
    branches: [main] # Or your default branch
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {} # Keep default permissions

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: HACS Validation Action
        uses: hacs/action@main
        with:
          category: "integration"
          # Add other inputs if needed, e.g., ignore specific checks

  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or the version HA core uses
      - name: Install hassfest
        run: pip install hassfest # This might need adjustment based on how hassfest is distributed for standalone use
      - name: Run hassfest
        run: python -m script.hassfest --action root # Command might vary
        # If direct hassfest is tricky, we might use a pre-built action like home-assistant/actions/hassfest@master
        # For now, let's try the direct approach and adjust if needed.
        # Fallback to home-assistant/actions/hassfest if the above is problematic:
        # uses: home-assistant/actions/hassfest@master
