name: Validate Integration

on:
  push:
    branches: [main] # Or your default branch
  pull_request:
    branches: [main] # Or your default branch
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {} # Keep default permissions

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: HACS Validation Action
        uses: hacs/action@main
        with:
          category: "integration"
          # Add other inputs if needed, e.g., ignore specific checks

  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hassfest Action
        uses: home-assistant/actions/hassfest@master
